### ISSUE TITLE
server error code -404

### ISSUE THREAD

**Issue by r6m** [shelomentsevd/telegram-api#21]
Hi
I'm trying to connect with my phone number (Iran `98`), but keep getting the `-404` error.
I realized the problem occurs while getting authKey in `makeAuthKey`.
After sending `set_client_DH_params` when it reads the response it returns an error with data of `-404`.

and of course connecting with a Russian phone number works great with no problem.

anyone facing this issue?

**Comment by ishanjain28** [comment]
Yeah, It works with fine with Indian phone numbers but repeatedly gives this error with Phone numbers from netherlands.
