### ISSUE TITLE
how to get photo from message with Media type TL_Photo ?

### ISSUE THREAD

**Issue by vtolstov** [shelomentsevd/telegram-api#24]
I don't see methods to get file or photo, may be i miss something?

**Comment by savely-krasovsky** [comment]
@vtolstov you should use `upload.getFile` method. Of course at first you should get `volume_id`, `local_id` and `secret`.

Example:
```golang
res, err := t.mtproto.InvokeSync(mtproto.TL_upload_getFile{
	Location: mtproto.TL_inputFileLocation{
		Volume_id: volumeId,
		Local_id:  localId,
		Secret:    secret,
	},
	Offset: offset,
	Limit:  65536,
})
if err != nil {
	return nil, err
}

switch (*res).(type) {
case mtproto.TL_upload_file:
	return (*res).(mtproto.TL_upload_file).Bytes, nil
}

return nil, errors.New("UNKNOWN TYPE RETURNED")
```

**Comment by vtolstov** [comment]
Wow THANKS!

**Comment by savely-krasovsky** [comment]
@vtolstov there is some problem right now. You could download files only from Data Center that you use. For Russia and CIS Telegram prefers second DC, for example. If you will try to download file from another DC you will get error `FILE_MIGRATE_dcNumber`.

But contributitions are welcome :)

**Comment by vtolstov** [comment]
Hmm. i have mtproto.TL_fileLocation and not mtproto.TL_inputFileLocation

**Comment by vtolstov** [comment]
and i'm from russia =)

**Comment by savely-krasovsky** [comment]
@vtolstov `mtproto.TL_fileLocation` you have in answer from Telegram with file. `TL_inputFileLocation` should used to request it.

**Comment by savely-krasovsky** [comment]
Example to get fileLocation variables:
```golang
if user, ok := res.(mtproto.TL_user); ok {
	if photo, ok := user.Photo.(mtproto.TL_userProfilePhoto); ok {
		if photoSmall, ok := photo.Photo_small.(mtproto.TL_fileLocation); ok {
			return Photo{
				photoSmall.Dc_id
				photoSmall.Volume_id,
				photoSmall.Local_id,
				photoSmall.Secret,
			}
		}
	}
}
```
And then use it `upload.getFile` method.
