### ISSUE TITLE
auth_key_unregistered error

### ISSUE THREAD

**Issue by amir-abbas** [shelomentsevd/telegram-api#8]
after while we get FLOOD_WAIT_X error or auth_key_unregistered error

**Comment by shelomentsevd** [comment]
Hi, @amir-abbas!
Pull request #7 should have fix this bug.
Do you still get error?

**Comment by amir-abbas** [comment]
Hi @shelomentsevd 
thank you for fix this bug but when change dc in auth_sentCode we get Phone_registered:false
not support switchDC.

**Comment by savely-krasovsky** [comment]
@amir-abbas we are working on it. You can use directly necessary DC right now.

**Comment by amir-abbas** [comment]
Hi @shelomentsevd @Lord-Protector 
I fixed this issue(switchDC ) but we have a new issue in reconnect function, we should disconnect first  but we stuck at this <-m.allDone

**Comment by amir-abbas** [comment]
@shelomentsevd @Lord-Protector 
thanks for your effort but please check disconnect function.this function does not work correctly.

**Comment by shelomentsevd** [comment]
Hi, @amir-abbas!
I'll check it on Monday. I am too busy this week. 
Sorry for the inconvenience.

**Comment by amir-abbas** [comment]
thanks

**Comment by shelomentsevd** [comment]
@amir-abbas I refactored Disconnect function and replaced allDone channel with WaitGroup, I think it should fix your problem. Let me know if you still have problem.

**Comment by amir-abbas** [comment]
@shelomentsevd 
Hi there, in [demo](https://github.com/shelomentsevd/telegramgo) application,  when we get EOF error and Reconnect process begin, this function
func (cli *TelegramCLI) Run() error {
	log.Println("CLI Update cycle started")
UpdateCycle:
	for {
		select {
		case <-cli.stop:
			log.Println("Update cycle stoped")
			break UpdateCycle
		case <-time.After(updatePeriod):
			cli.processUpdates()
		}
	}

	log.Println("CLI Update cycle finished")
	return nil
}

does not work

**Comment by shelomentsevd** [comment]
@amir-abbas I think this is a [telegramgo](https://github.com/shelomentsevd/telegramgo) problem, not a mtproto lib.
